.TH Sequencer66 "March 2021" "Version 0.92.2" "Seq66 Manual Page"

.SH NAME
Seq66 - Real-time live MIDI sequencer refactored from Seq24, Native JACK

.SH SYNOPSIS
.B qseq66
[\fIOPTIONS\fP] [\fIFILENAME\fP]
.B seq66cli
[\fIOPTIONS\fP] [\fIFILENAME\fP]
.B qpseq66
[\fIOPTIONS\fP] [\fIFILENAME\fP]
on Windows.

.SH DESCRIPTION
.PP
\fISeq66\fP is the updated version of Sequencer64.
See "man Sequencer66" for full information on this application.

.SH SEE ALSO
See the sequencer64-doc project for a full manual.  Most of it still applies to
Seq66, but Seq66 uses only a Qt UI or command-line interface.

