.TH Sequencer66 "March 2021" "Version 0.92.2" "Seq66 Manual Page"

.SH NAME
Seq66 - Real-time live MIDI sequencer refactored from Seq24, Native JACK

.SH SYNOPSIS
.B qseq66
[\fIOPTIONS\fP] [\fIFILENAME\fP]
.B seq66cli
[\fIOPTIONS\fP] [\fIFILENAME\fP]
.B qpseq66
[\fIOPTIONS\fP] [\fIFILENAME\fP]
on Windows.

.SH DESCRIPTION
.PP
\fISeq66\fP is the comprehensively updated version of Sequencer64.
See "man Sequencer66" for full information on this application.

.SH SEE ALSO
See the Seq66/Sequencer66 man page for command-line options.
See the Seq66 PDF user's manual in the 'doc' directory for even more
information.  It is very comprehensive and is indexed.
