.TH Sequencer66 "July 2020" "Version 0.90.4" "Seq66 Manual Page"

.SH NAME
Seq66 - Real-time live MIDI sequencer refactored from Seq24, Native JACK

.SH SYNOPSIS
.B qseq66
[\fIOPTIONS\fP] [\fIFILENAME\fP]
.B seq66cli
[\fIOPTIONS\fP] [\fIFILENAME\fP]

.SH DESCRIPTION
.PP
\fISeq66\fP is the updated version of Seq66.
See "man sequencer66" for full information on this application.

.SH SEE ALSO
See the main man page, sequencer66, for more information.
See the sequencer64-doc project for a full manual.  Most of it still applies to
Seq66, but Seq66 uses only a Qt UI or command-line interface.

