.TH Seq66cli "January 2021" "Version 0.91.5" "Seq66 Command-Line Manual Page"

.SH NAME
Seq66 - Real-time live MIDI sequencer refactored from Seq24, Native JACK

.SH SYNOPSIS
.B seq66cli
[\fIOPTIONS\fP] [\fIFILENAME\fP]

.SH DESCRIPTION
.PP
\fIseq66cli\fP is the command-line (no GUI)
native JACK version of Seq66/Sequencer66.  Please
see "man Sequencer66" for full information on this application. This
application is known by the names "Seq66", "Sequencer66", and depending on the
operating environment or build, "qseq66" (the main Linux version) or
"qpseq66.exe" (Windows).

.SH SEE ALSO
See the Seq66/Sequencer66 man page for command-line options.
See the Sequencer64-doc project for even more information. It is documentation
for the legacy project, but most of the documentation still applies to Seq66.

