.TH Sequencer66 "May 2023" "Version 0.99.5" "Seq66 Alternate Manual Page"

.SH NAME
Sequencer66 - Real-time live MIDI sequencer refactored from Seq24, Native JACK

.SH SYNOPSIS
.B qseq66
[\fIOPTIONS\fP] [\fIFILENAME\fP]
.B seq66cli
[\fIOPTIONS\fP] [\fIFILENAME\fP]
.B qpseq66
[\fIOPTIONS\fP] [\fIFILENAME\fP]
on Windows.

.SH DESCRIPTION
.PP
\fISequencer66\fP is the comprehensively updated version of Sequencer64.
See "man sequencer66" for full information on this application.

.SH SEE ALSO
See the Seq66 man page ("man seq66") for command-line options.
Use the "--help" option for a comprehensive list.
See the Seq66 PDF user's manual in the 'doc' directory for even more
information.  It is very comprehensive and is indexed.
