#!/bin/bash
#------------------------------------------------------------------------------
##
# \file        configure-clang
# \library     bin
# \author      Chris Ahlstrom
# \date        2023-12-06 to 2023-12-08
# \version     $Revision$
# \license     GNU GPLv2 or above
#
# This script tries to set up got building Seq66 with clang.
#
#------------------------------------------------------------------------------

# export CFLAGS=" -flto -std=gnu99 "
# export LDFLAGS=" -flto -fuse-ld=gold "
# export RANLIB=llvm-ranlib
# export QMAKESPEC="linux-llvm"
# export QMAKESPEC="linux-clang"

CLANGVER=-12

CC="clang$CLANGVER" CXX="clang++$CLANGVER" ./configure $*

#******************************************************************************
# qbuild (Seq66)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 wm=4 et ft=sh
#------------------------------------------------------------------------------

