#!/bin/bash
#------------------------------------------------------------------------------
##
# \file        configure-clang
# \library     bin
# \author      Chris Ahlstrom
# \date        2023-12-06 to 2023-12-16
# \version     $Revision$
# \license     GNU GPLv2 or above
#
# This script tries to set up got building Seq66 with clang.
#
#------------------------------------------------------------------------------
#
# export CFLAGS=" -flto -std=gnu99 "
# export LDFLAGS=" -flto -fuse-ld=gold "
# export RANLIB=llvm-ranlib
# export QMAKESPEC="linux-llvm"
# export QMAKESPEC="linux-clang"
#
# It's better to use the generic names, even the user must add soft-links to
# the desired version.
#
# CLANGVER=
# CC="clang$CLANGVER" CXX="clang++$CLANGVER" ./configure $*

CC=clang CXX=clang++ ./configure $*

if [ $? != 0 ] ; then
   echo "CC=clang CXX=clang++ ./configure $* failed"
else
   echo "CC=clang CXX=clang++ ./configure $* is complete"
fi

#******************************************************************************
# qbuild (Seq66)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 wm=4 et ft=sh
#------------------------------------------------------------------------------

