#!/bin/bash
#
#******************************************************************************
# startjack
#------------------------------------------------------------------------------
##
# \file        startjack
# \library     Home/Audio
# \author      Chris Ahlstrom
# \date        2020-12-08
# \update      2020-12-10
# \version     $Revision$
#
#   This script provides a way to make a fast JACK setup on Linux.  See:
#
#         https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit
#
#   Requires the python-dbus package to be installed.  The HD2 values available
#   are found in /proc/asound/cards:  PCH, HDMI, NVidia, CODEC, etc.  The "dps"
#   rate can be 44100, 48000, and higher.  The "nperiods" value should be 2 for
#   motherboard, PCI, PCI-X audio, and 3 for USB audio.
#
#------------------------------------------------------------------------------

HD2=PCH

if [ "$1" == "kill" ] ; then

    killall qjackctl
    a2j_control --stop
    a2j_control --exit
    jack_control exit

else

    jack_control start
    jack_control ds alsa
    jack_control dps device hw:$HD2
    jack_control dps rate 48000
    jack_control dps nperiods 2
    jack_control dps period 64
    echo "Waiting 10 seconds for jack_control to settle..."
    sleep 10
    a2j_control --ehw
    a2j_control --start
    echo "Waiting 10 seconds for a2j_control to settle..."
    sleep 10
    echo "Starting qjackctl..."
    qjackctl &

fi

#------------------------------------------------------------------------------
# vim: ft=sh
#------------------------------------------------------------------------------
