#!/bin/bash
#------------------------------------------------------------------------------
##
# \file        timid
# \library     bin
# \author      Chris Ahlstrom
# \date        2021-04-19 to 2021-05-04
# \version     $Revision$
# \license     GNU GPLv2 or above
#
#  This script runs timidity, so one can avoid having to deal with timidity as
#  a service.  Starts it under ALSA as a daemon, not a service.
#
#     -Oj            Output to JACK.
#     -Os            Output to ALSA.
#     -Od            Output to audio device.
#     -iA            Launch as an ALSA sequencer client
#     --background   Start as a daemon.
#
#  See https://wiki.debian.org/AlsaMidi
#
#------------------------------------------------------------------------------

SETTLETIME="3"

if [ "$1" == "kill" ] ; then

   SETTLETIME="1"
   killall timidity

elif [ "$1" == "jack" ] ; then

   timidity -Oj -iA --background

else

   timidity -Os -iA --background

fi

echo "Waiting $SETTLETIME seconds to settle..."
sleep $SETTLETIME
aplaymidi -l

#******************************************************************************
# qbuild (Seq66)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 wm=4 et ft=sh
#------------------------------------------------------------------------------

