#******************************************************************************
# virmidi.conf (seq66)
#------------------------------------------------------------------------------
##
# \file           virmidi.conf
# \library        seq66
# \author         Chris Ahlstrom
# \date           2026-09-18
# \update         2026-09-19
# \version        $Revision$
# \license        $XPC_SUITE_GPL_LICENSE$
#
#     The above is modified by the following to remove even the mild GPL
#     restrictions:
#
#     This file is used to enable the snd_virmidi and snd_seq_virmidi
#     modules at boot time.  Copy it to the /etc/modules-load.d directory.
#
#     /etc/modules is obsolete and has been replaced by /etc/modules-load.d/.
#     Please see modules-load.d(5) and modprobe.d(5) for details.
#
#     One could create another .conf file containing options such as the
#     following, and copy it to /etc/modprobe.d to pass the options to udev.
#
#        options snd-virmidi index=1
#        options snd-virmidi midi_devs=2     (instead of 4)
#
#     The index number is not necessary, and it would vary depending
#     on the MIDI devices already present on the system.
#
#------------------------------------------------------------------------------

snd-virmidi

#******************************************************************************
# virmidi.conf (seq66)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 wm=4 et ft=conf
#------------------------------------------------------------------------------
