#******************************************************************************
# virmidi-options.conf (seq66)
#------------------------------------------------------------------------------
##
# \file           virmidi-options.conf
# \library        seq66
# \author         Chris Ahlstrom
# \date           2026-09-19
# \update         2026-09-19
# \version        $Revision$
# \license        $XPC_SUITE_GPL_LICENSE$
#
#     The above is modified by the following to remove even the mild GPL
#     restrictions:
#
#     This file can be used to pass options to snd-virmidi.
#     Copy it to /etc/modprobe.d to pass the options to udev.
#
#        options snd-virmidi index=1
#
#     The index number is not necessary, and it would vary depending
#     on the MIDI devices already present on the system.
#
#------------------------------------------------------------------------------

options snd-virmidi midi_devs=2

#******************************************************************************
# virmidi-options.conf (seq66)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 wm=4 et ft=conf
#------------------------------------------------------------------------------
