#!/bin/bash
#
#******************************************************************************
# make-helper (generic)
#------------------------------------------------------------------------------
##
# \file       	make-helper
# \library    	notes directory
# \author     	Chris Ahlstrom
# \date       	2015-08-08
# \update     	2019-05-11
# \version    	$Revision$
# \license    	$XPC_SUITE_GPL_LICENSE$
#
#     This file creates the doxygen documentation for the notes subdirectory.
#
#------------------------------------------------------------------------------

echo "Running Doxygen on the notes target, in the make-helper script."
echo "$DOXYGEN notes.cfg > dox-progress.log 2> dox-errors.log ..."
doxygen notes.cfg > dox-progress.log 2> dox-errors.log
sed -e 's/letterpaper,/letterpaper,margin=2cm,/' -i latex/refman.tex

#  This breaks too easily, so now we descend and run the commands a few
#  times, similar to what the latex/make-helper does.  Bleh!

make --directory=latex pdf >> dox-progress.log 2>> dox-errors.log

# pushd latex
# pdflatex refman
# makeindex refman.idx
# pdflatex refman
# makeindex refman.idx
# pdflatex refman
# makeindex refman.idx
# pdflatex refman
# makeindex refman.idx
# pdflatex refman
# makeindex refman.idx
# popd

# Optimize the PDF to cut down on its size.

../optimize seq66_developer_notes >> dox-progress.log 2>> dox-errors.log

cp latex/refman.pdf seq66_developer_notes.pdf

#******************************************************************************
# make-helper (generic)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 et ft=make
#------------------------------------------------------------------------------
