#!/bin/bash
#
#******************************************************************************
# make-helper (generic)
#------------------------------------------------------------------------------
##
# \file       	make-helper
# \library    	seq_portmidi directory
# \author     	Chris Ahlstrom
# \date       	2019-05-11
# \update     	2019-05-11
# \version    	$Revision$
# \license    	$XPC_SUITE_GPL_LICENSE$
#
#     This file creates the doxygen documentation for the seq_portmidi
#     subdirectory.
#
#------------------------------------------------------------------------------

echo "Running Doxygen on the seq_portmidi target, in the make-helper script."
echo "$DOXYGEN seq_portmidi.cfg > dox-progress.log 2> dox-errors.log ..."
doxygen seq_portmidi.cfg > dox-progress.log 2> dox-errors.log
sed -e 's/letterpaper,/letterpaper,margin=2cm,/' -i latex/refman.tex

#  This breaks too easily, so now we descend and run the commands a few
#  times, similar to what the latex/make-helper does.  Bleh!

make --directory=latex pdf >> dox-progress.log 2>> dox-errors.log

# Optimize the PDF to cut down on its size.

../optimize seq_portmidi >> dox-progress.log 2>> dox-errors.log

cp latex/refman.pdf seq_portmidi.pdf

#******************************************************************************
# make-helper (generic)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 et ft=make
#------------------------------------------------------------------------------
