#!/bin/bash
#
#******************************************************************************
# packages (Seq66)
#------------------------------------------------------------------------------
##
# \file       	packages
# \library    	Seq66
# \author     	Chris Ahlstrom
# \date       	2018-09-29
# \update     	2021-04-17
# \version    	$Revision$
# \license    	$XPC_SUITE_GPL_LICENSE$
#
#  Packs up the current project directory, makes an NSIS package installer.
#  Written solely to automate some tedious stuff needed for an official
#  Seq66 release.
#
#-----------------------------------------------------------------------------

RELEASEMAJOR="0.93"
RELEASEMINOR="0"
RELEASENUMBER="$RELEASEMAJOR.$RELEASEMINOR"
REVNUMBER="0"
DODRYRUN="no"
DORELEASE="no"

if [ "$1" == "--help" ] || [ "$1" == "help" ] ; then

   cat << E_O_F

packages 0.6 2021-04-17

Usage:  ./packages [--dry-run] [--release [0.93.0] ]

This script packs the contents of the current directory into the following
packages:

E_O_F

else

   while [ "$1" != "" ] ; do

      case "$1" in

        --dry-run)
            DODRYRUN="yes"
            ;;

        --clean)
            DOCLEAN="yes"
            ;;

        --no-clean)
            DOCLEAN="no"
            ;;

        --release)
            shift
            DORELEASE="yes"
            if [ "$1" != "" ] ; then
               RELEASENUMBER="$1"
            fi
            ;;

        *)
            ;;

      esac
      shift
   done

fi

PACKAGENAME="qpseq66-release-package-$RELEASENUMBER.7z"
# INSTALLERNAME="seq66_setup_$RELEASENUMBER-$REVNUMBER.exe"
# ZIPNAME="qpseq66-portable-$RELEASENUMBER-$REVNUMBER.zip"
INSTALLERNAME="seq66_setup_$RELEASENUMBER.exe"
ZIPNAME="qpseq66-portable-$RELEASENUMBER.zip"
TARNAME="seq66-master-rtmidi-$RELEASENUMBER.tar.xz"

if [ "$DODRYRUN" == "yes" ] ; then

   echo "DRY RUN, release = '$RELEASENUMBER'...."

   if [ -f configure ] ; then
      echo " "
      echo "Making a standard Linux source/configure tarball..."
      echo "$ ./pack --release rtmidi $RELEASENUMBER"
      echo "$ mv ../$TARNAME ../seq66-packages/latest"
   else
      echo " "
      echo "WARNING:  'configure' does not exist, cannot make a standard Linux"
      echo "          source tarball! Aborting."
      exit 1
   fi

   echo "Extracting Windows deployment package..."
   echo "$ 7z x -y $PACKAGENAME"

#  echo "$ mv $PACKAGENAME .."

   echo "$ pushd nsis"
   echo "Building NSIS installer for release $RELEASENUMBER..."
   echo "$ makensis Seq66Setup.nsi"
   echo "$ popd"

   echo "$ mkdir -p qpseq66"
   echo "$ cp -r release/* qpseq66"
   echo "$ rm -rf release"
   echo "$ cp qpseq66/$INSTALLERNAME ../seq66-packages/latest"
   echo "Copying qpseq66/$INSTALLERNAME to ../seq66-packages/latest..."

   echo "Making a portable Zip package..."
   echo "$ zip -q -u -r $ZIPNAME qpseq66/"
   echo "Copying qpseq66/$ZIPNAME to ../seq66-packages/latest..."
   echo "$ cp $ZIPNAME ../seq66-packages/latest"
   echo "$ ls -lrt ../seq66-packages/latest"

else

   if [ -f configure ] ; then
      echo " "
      echo "Making a standard Linux source/configure tarball..."
      ./pack --release rtmidi $RELEASENUMBER
      mv ../$TARNAME ../seq66-packages/latest
   else
      echo " "
      echo "WARNING:  'configure' does not exist, cannot make a standard Linux"
      echo "          source tarball! Aborting."
      exit 1
   fi

   echo "Extracting Windows deployment package..."
   7z x -y $PACKAGENAME

#  mv $PACKAGENAME ..

   pushd nsis
   echo "Building NSIS installer for release $RELEASENUMBER..."
   makensis Seq66Setup.nsi
   popd

   mkdir -p qpseq66
   cp -r release/* qpseq66
   rm -rf release/

   echo "Copying qpseq66/$INSTALLERNAME to ../seq66-packages/latest..."
   cp qpseq66/$INSTALLERNAME ../seq66-packages/latest

   echo "Making a portable Zip package..."
   zip -q -u -r $ZIPNAME qpseq66/
   echo "Copying qpseq66/$ZIPNAME to ../seq66-packages/latest..."
   cp $ZIPNAME ../seq66-packages/latest
   ls -lrt ../seq66-packages/latest

fi

#******************************************************************************
# packages (Seq66)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 et ft=sh
#------------------------------------------------------------------------------
