# https://gensoft.pasteur.fr/docs/mesa/19.0.8/meson.html#cross-compilation
#
# Meson supports cross-compilation by specifying a number of binary paths and
# settings in a file and passing this file to meson or meson configure with the
# --cross-file parameter.
#
# This file can live at any location, but you can use the bare filename
# (without the folder path) if you put it in $XDG_DATA_HOME/meson/cross or
# ~/.local/share/meson/cross
#
# Below are a few example of cross files, but keep in mind that you will likely
# have to alter them for your system.

# 32-bit build on x86 linux:

[binaries]

c = '/usr/bin/gcc'
cpp = '/usr/bin/g++'
ar = '/usr/bin/gcc-ar'
strip = '/usr/bin/strip'
pkgconfig = '/usr/bin/pkg-config-32'
llvm-config = '/usr/bin/llvm-config32'

[properties]

c_args = ['-m32']
c_link_args = ['-m32']
cpp_args = ['-m32']
cpp_link_args = ['-m32']

[host_machine]

system = 'linux'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'

# 64-bit build on ARM linux: 

[binaries]

c = '/usr/bin/aarch64-linux-gnu-gcc'
cpp = '/usr/bin/aarch64-linux-gnu-g++'
ar = '/usr/bin/aarch64-linux-gnu-gcc-ar'
strip = '/usr/bin/aarch64-linux-gnu-strip'
pkgconfig = '/usr/bin/aarch64-linux-gnu-pkg-config'
exe_wrapper = '/usr/bin/qemu-aarch64-static'

[host_machine]

system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

# 64-bit build on x86 windows:

[binaries]
c = '/usr/bin/x86_64-w64-mingw32-gcc'
cpp = '/usr/bin/x86_64-w64-mingw32-g++'
ar = '/usr/bin/x86_64-w64-mingw32-ar'
strip = '/usr/bin/x86_64-w64-mingw32-strip'
pkgconfig = '/usr/bin/x86_64-w64-mingw32-pkg-config'
exe_wrapper = 'wine'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'i686'
endian = 'little'


# https://github.com/GabrielGanne/meson-cross-compilation-example

[constants]

prefix = 'aarch64-linux-gnu-'

[binaries]

c = prefix + 'gcc'
cpp = prefix + 'cpp'
ar = prefix + 'gcc-ar'
strip = prefix + 'strip'
pcap-config = ''

[host_machine]

system = 'linux'
cpu_family = 'aarch64'
cpu = 'armv8-a'
endian = 'little'

[properties]

# Generate binaries that are portable across all Armv8 machines
implementer_id = 'generic'
part_number = 'generic'
max_lcores = 256
max_numa_nodes = 4
