#!/bin/bash
#
# 2026-04-01 to 2026-04-01
#
# Runs vimdiff in a larger terminal. Under tmux, sometimes one cannot
# get gvim to run from in a terminal.
#

/usr/bin/urxvt -geometry 164x56 -e vimdiff $1 $2  &

# vim: ts=3 sw=3 et ft=sh
