#if ! defined SEQ66_SYSEX_HPP
#define SEQ66_SYSEX_HPP

/*
 *  This file is part of seq66.
 *
 *  seq66 is free software; you can redistribute it and/or modify it under the
 *  terms of the GNU General Public License as published by the Free Software
 *  Foundation; either version 2 of the License, or (at your option) any later
 *  version.
 *
 *  seq66 is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 *  details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with seq66; if not, write to the Free Software Foundation, Inc., 59 Temple
 *  Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * \file          sysex.hpp
 *
 *  This module declares the right version of the sysex header for the
 *  current API.
 *
 * \library       seq66 application
 * \author        Chris Ahlstrom
 * \date          2026-09-20
 * \updates       2026-09-21
 * \license       GNU GPLv2 or above
 *
 */

#include <string>                       /* std::string <>                   */

#include "seq66-config.h"               /* generated by Meson               */
#include "midi/midibytes.hpp"           /* seq66::midibytes, etc.           */

namespace seq66
{

/**
 *  Defines the value used for sleeping, in microseconds, and the
 *  size of System Exclusive chunks..
 */

#if SEQ66_HAVE_ALSA

const int c_alsa_sysex_sleep_us   { 40000 };            /* 20 to 50 ms: 40  */
const int c_alsa_sysex_chunk      {   256 };

inline int
sysex_sleep_us ()
{
    return c_alsa_sysex_sleep_us;
}

inline int
sysex_chunk ()
{
    return c_alsa_sysex_chunk;
}

#elif SEQ66_HAVE_JACK

const int c_jack_sysex_sleep_us   { 40000 };
const int c_jack_sysex_chunk      {   256 };

inline int
sysex_sleep_us ()
{
    return c_jack_sysex_sleep_us;
}

inline int
sysex_chunk ()
{
    return c_jack_sysex_chunk;
}

#else

const int c_other_sysex_sleep_us  { 40000 };
const int c_other_sysex_chunk     {   256 };

inline int
sysex_sleep_us ()
{
    return c_other_sysex_sleep_us;
}

inline int
sysex_chunk ()
{
    return c_other_sysex_chunk;
}

#endif

/*--------------------------------------------------------------------------
 * Free functions
 *--------------------------------------------------------------------------*/

extern std::string mmc_commands (int index);
extern std::string generic_sysex (const midibytes & mbuf);

}           // namespace seq66

#endif      // SEQ66_SYSEX_HPP

/*
 * sysex.hpp
 *
 * vim: sw=4 ts=4 wm=4 et ft=cpp
 */
